language: php

sudo: false

matrix:
    include:
        - php: 5.5
          env: SYMFONY_VERSION="2.7.*"
        - php: 5.6
          env: SYMFONY_VERSION="2.8.*"
        - php: 7.0
          env: SYMFONY_VERSION="3.0.*"
        - php: hhvm
          env: SYMFONY_VERSION="3.0.*"

before_install:
    - composer self-update

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer update --prefer-dist --no-interaction
